/*
 IDEA mysql-2-h2插件 生成的SQL 脚本，请根据实际情况调整。

 Source Server Adjusted for: H2 Database Engine
*/

SET
MODE MySQL; -- 设置H2以模拟MySQL的模式，以便更好地兼容


CREATE TABLE user_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'id',
    userAccount  VARCHAR(256)                           NOT NULL COMMENT '账号',
    userPassword VARCHAR(512)                           NOT NULL COMMENT '密码',
    unionId      VARCHAR(256) NULL COMMENT '微信开放平台id',
    mpOpenId     VARCHAR(256) NULL COMMENT '公众号openId',
    userName     VARCHAR(256) NULL COMMENT '用户昵称',
    userAvatar   VARCHAR(1024) NULL COMMENT '用户头像',
    userProfile  VARCHAR(512) NULL COMMENT '用户简介',
    userRole     VARCHAR(256) DEFAULT 'user'            NOT NULL COMMENT '用户角色：user/admin/ban',
    createTime   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    updateTime   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
    isDelete     BOOLEAN      DEFAULT FALSE             NOT NULL COMMENT '是否删除',
    INDEX        idx_unionId (unionId)
);

-- 表信息表
CREATE TABLE table_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'id',
    name          VARCHAR(512) NULL COMMENT '名称',
    content       TEXT NULL COMMENT '表信息（json）',
    reviewStatus  INT       DEFAULT 0                 NOT NULL COMMENT '状态（0-待审核, 1-通过, 2-拒绝）',
    reviewMessage VARCHAR(512) NULL COMMENT '审核信息',
    userId        BIGINT                              NOT NULL COMMENT '创建用户 id',
    createTime    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    updateTime    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
    isDelete      BOOLEAN   DEFAULT FALSE             NOT NULL COMMENT '是否删除'
);

-- 字段信息表
CREATE TABLE field_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'id',
    name          VARCHAR(512) NULL COMMENT '名称',
    fieldName     VARCHAR(512) NULL COMMENT '字段名称',
    content       TEXT NULL COMMENT '字段信息（json）',
    reviewStatus  INT       DEFAULT 0                 NOT NULL COMMENT '状态（0-待审核, 1-通过, 2-拒绝）',
    reviewMessage VARCHAR(512) NULL COMMENT '审核信息',
    userId        BIGINT                              NOT NULL COMMENT '创建用户 id',
    createTime    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    updateTime    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
    isDelete      BOOLEAN   DEFAULT FALSE             NOT NULL COMMENT '是否删除'
);

-- SQL 执行记录表
CREATE TABLE level_info
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'id',
    sqlContent       VARCHAR(512) NULL COMMENT '执行 SQL 的内容',
    sqlAnalyzeResult VARCHAR(512) NULL COMMENT 'SQL 分析结果',
    reviewStatus     INT       DEFAULT 0                 NOT NULL COMMENT '状态（0-待审核, 1-通过, 2-拒绝）',
    reviewMessage    VARCHAR(512) NULL COMMENT '审核信息',
    userId           BIGINT                              NOT NULL COMMENT '创建用户 id',
    createTime       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    updateTime       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
    isDelete         BOOLEAN   DEFAULT FALSE             NOT NULL COMMENT '是否删除'
);

-- 关卡题目表
CREATE TABLE topic_level
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT 'id',
    title       VARCHAR(64) NULL COMMENT '关卡中文名',
    initSQL     VARCHAR(512) NULL COMMENT '初始化 SQL',
    mdContent   TEXT                                NOT NULL COMMENT '关卡教程 Markdown 文档',
    defaultSQL  VARCHAR(512) NULL COMMENT '关卡初始化后默认执行的语句，一般是查询全表',
    answer      VARCHAR(512) NULL COMMENT '关卡标准答案',
    hint        VARCHAR(256) NULL COMMENT '关卡提示',
    type        VARCHAR(256) NULL COMMENT '关卡类别，custom 自定义、system 系统',
    nextLevelId BIGINT NULL COMMENT '下一关卡的 id',
    userId      BIGINT                              NOT NULL COMMENT '创建用户 id',
    createTime  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    updateTime  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
    isDelete    BOOLEAN   DEFAULT FALSE             NOT NULL COMMENT '是否删除'
);
